### ISSUE TITLE
Mason not initializing without context.xml

### ISSUE THREAD

**Issue by d3ep4k** [metamug/mason#103]
26-Oct-2019 00:36:11.613 SEVERE [main] com.metamug.mason.service.ConnectionProvider.getMasonDatasource null
	javax.naming.NamingException: Unexpected exception resolving reference [Root exception is java.lang.RuntimeException: java.lang.reflect.InvocationTargetException]
		at org.apache.naming.NamingContext.lookup(NamingContext.java:856)
		at org.apache.naming.NamingContext.lookup(NamingContext.java:159)
		at org.apache.naming.NamingContext.lookup(NamingContext.java:827)
		at org.apache.naming.NamingContext.lookup(NamingContext.java:173)
		at com.metamug.mason.service.ConnectionProvider.getMasonDatasource(ConnectionProvider.java:533)
		at com.metamug.mason.service.ConnectionProvider.<init>(ConnectionProvider.java:542)
		at com.metamug.mason.Router.init(Router.java:747)

**Comment by d3ep4k** [comment]
RequestProcessable interface requests a DataSource. so not providing a datasource isn't an option currently. Or else the datasource object should be assigned null in case context.xml isn't provided
