### ISSUE TITLE
XRequest - response containing unknown characters throws exception

### ISSUE THREAD

**Issue by ancode4** [metamug/mason#66]
Resource:
```
<m:request method="GET">

    <m:xrequest var="xreqResult" method="GET" url="http://server.metamug.net:7000/bookmark/v1.0/conversation?date=2014-08-21"> . 
    </m:xrequest>

     <c:set target="${masonOutput}" property="internal" value="${xreqResult}"/>
</m:request>
```

Error trace:
com.metamug.mason.tag.request.RequestTagHandler.processOutput Not an ISO 8859-1 character: [�]
 java.io.CharConversionException: Not an ISO 8859-1 character: [�]
	at javax.servlet.ServletOutputStream.print(ServletOutputStream.java:78)
	at com.metamug.mason.tag.request.RequestTagHandler.processOutput(RequestTagHandler.java:598)
	at com.metamug.mason.tag.request.RequestTagHandler.doEndTag(RequestTagHandler.java:567)

**Comment by ancode4** [comment]
Closed in https://github.com/metamug/mason/commit/552a52aa93fab3953721d90771d0c0d8fae4eca9
