### ISSUE TITLE
Null Pointer Exception com.metamug.mason.tag.ExceptionTagHandler.dbLogErorr

### ISSUE THREAD

**Issue by d3ep4k** [metamug/mason#68]
```json
{"message":"An exception occurred processing [/WEB-INF/resources/error/errorpage.jsp] at line [4] Unable to display JSP extract. Probably due to an XML parser bug (see Tomcat bug 48498 for details). Stacktrace:","status":422}
```

Unable to display JSP extract. Probably due to an XML parser bug (see Tomcat bug 48498 for details).

Stacktrace:
                at org.apache.jasper.servlet.JspServletWrapper.handleJspException(JspServletWrapper.java:625)
                at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:514)
                at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:385)
                at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:329)
                at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
                at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
                at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:712)
                at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:459)
                at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:384)
                at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:312)
                at org.apache.jasper.runtime.PageContextImpl.forward(PageContextImpl.java:530)
                at org.apache.jasper.runtime.PageContextImpl.handlePageException(PageContextImpl.java:624)
                at org.apache.jsp.WEB_002dINF.resources.v1_0.stock_jsp._jspService(stock_jsp.java:158)
                at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
                at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
                at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:476)
                ... 37 more
        Caused by: java.lang.NullPointerException
                at com.metamug.mason.tag.ExceptionTagHandler.dbLogErorr(ExceptionTagHandler.java:834)
                at com.metamug.mason.tag.ExceptionTagHandler.logError(ExceptionTagHandler.java:774)
                at com.metamug.mason.tag.ExceptionTagHandler.doEndTag(ExceptionTagHandler.java:753)
                at org.apache.jsp.WEB_002dINF.resources.error.errorpage_jsp._jspx_meth_mtg_005fexception_005f0(errorpage_jsp.java:153)
                at org.apache.jsp.WEB_002dINF.resources.error.errorpage_jsp._jspService(errorpage_jsp.java:117)
                at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
                at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
                at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:476)
                ... 55 more

**Comment by kaisteel** [comment]
Can you add steps to reproduce this?

**Comment by d3ep4k** [comment]
Try exporting a hsqldb webapp from console and load it in tomcat 9.

**Comment by kaisteel** [comment]
But all the console generated webapps are already running in Tomcat 9, so why load it in tomcat 9 again? Perhaps did you mean to say that export the web app from the console and then try to load it another Tomcat 9 server.

**Comment by d3ep4k** [comment]
Yes exactly. Currently this doesn't work. @ancode4  decided not to support HSQLDB export.

**Comment by d3ep4k** [comment]
This error again came up when mysql connection failed. The error was gone when the connection was established.
